In [3]:
import pandas as pd

In [4]:
cuisine = "Korean"
recp2mol = pd.read_csv('./'+cuisine+'/000_recipe_molecule_edges.csv')
molweight = pd.read_csv('./'+cuisine+'/001_molecule_weight.csv')
mol2recp = pd.read_csv('./'+cuisine+'/002_molecule_recipe_edges.csv')

In [5]:
display(recp2mol.head(10))
display(molweight.head(10))
display(mol2recp.head(10))

,recipe_id,name,rank,molecule,molecule_name,flavor_profile,p
0,3,Kombu Tea Grilled Chicken Thigh,1,6561,Isobutyraldehyde,"{'malt', 'floral', 'fresh', 'pungent', 'aldehy...",0.019622
1,3,Kombu Tea Grilled Chicken Thigh,2,7284,2-Methylbutyraldehyde,"{'nutty', 'cocoa', 'almond', 'musty', 'coffee'}",0.019622
2,3,Kombu Tea Grilled Chicken Thigh,3,11552,3-Methylbutanal,"{'fatty', 'sour', 'malt', 'aldehydic', 'ethere...",0.019622
3,3,Kombu Tea Grilled Chicken Thigh,4,264,butyric acid,"{'fruit', 'sharp', 'rancid', 'sweat', 'cheese'...",0.011111
4,3,Kombu Tea Grilled Chicken Thigh,5,2758,Eucalyptol,"{'sweet', 'pepper', 'eucalyptus', 'camphor', '...",0.011111
5,3,Kombu Tea Grilled Chicken Thigh,6,2879,P-Cresol,"{'smoke', 'phenol', 'narcissus', 'mimosa', 'me...",0.011111
6,3,Kombu Tea Grilled Chicken Thigh,7,3314,eugenol,"{'woody', 'cinnamon', 'spicy', 'sweet', 'honey...",0.011111
7,3,Kombu Tea Grilled Chicken Thigh,8,6736,3-Methylindole,"{'very strong', 'civet', 'indole', 'fecal', 'm...",0.011111
8,3,Kombu Tea Grilled Chicken Thigh,9,7460,Alpha-Phellandrene,"{'woody', 'peppery', 'terpene', 'turpentine', ...",0.011111
9,3,Kombu Tea Grilled Chicken Thigh,10,7991,Valeric acid,"{'sweat', 'rancid', 'sickening', 'acidic', 'pu...",0.011111

,molecule,weight,molecule_name,flavor_profile,rank
0,644104,315.157448,CID 644104,"{'very mild', 'grassy'}",1
1,1130,313.214742,thiamine,{'bitter'},2
2,8094,289.176750,Heptanoic Acid,"{'sweat', 'rancid', 'sour', 'cheesy', 'cheese'}",3
3,6202,242.719310,Thiamine Hydrochloride,"{'bitter', 'mild', 'sour'}",4
4,247,117.873094,betaine,{'bland'},5
5,107971,30.948471,Daidzin,{'bitter'},6
6,5281708,30.497906,daidzein,{'bitter'},7
7,5284639,30.436686,NSC5112,{'bitter'},8
8,31260,25.112539,3-Methyl-1-butanol,"{'banana', 'burnt', 'fruity', 'malt', 'whiskey...",9
9,650,24.849545,"2,3-butanedione","{'strong', 'oily', 'creamy', 'sweet', 'butter'...",10

,molecule,molecule_name,flavor_profile,rank,recipe_id,name,p
0,4,1-Aminopropan-2-ol,{'fishy'},1,36376,Marinade Turkey Chicken Recipe,0.005254
1,4,1-Aminopropan-2-ol,{'fishy'},2,310894,Korean Barbecue Marinade,0.004738
2,4,1-Aminopropan-2-ol,{'fishy'},3,222530,Hoisin Chili Marinade For Chicken/Pork Recipe,0.004012
3,4,1-Aminopropan-2-ol,{'fishy'},4,297566,Korean BBQ Marinade,0.003592
4,4,1-Aminopropan-2-ol,{'fishy'},5,482384,Korean BBQ Marinade,0.003404
5,4,1-Aminopropan-2-ol,{'fishy'},6,80812,Asian Pork with Noodles,0.002844
6,4,1-Aminopropan-2-ol,{'fishy'},7,548708,"Beef Ribs, Korean Style Recipe",0.002838
7,4,1-Aminopropan-2-ol,{'fishy'},8,32951,Teriyaki Grilled Beef Flat Ribs,0.002242
8,4,1-Aminopropan-2-ol,{'fishy'},9,201334,Tea Smoked Asian Style Beef Short Ribs,0.002215
9,4,1-Aminopropan-2-ol,{'fishy'},10,165474,Barbecued Beef (Korean Bul Kogi) Recipe,0.001939