In [1]:
import pandas as pd

In [4]:
african_mol = pd.read_csv('./African_molecule_nodes.csv')
african_recipe_mol_edge = pd.read_csv('./African_recipe_molecule_edges.csv')

In [5]:
african_mol.head(3)

   molecule_id      weight
0         1130  159.334117
1       644104  159.123112
2         8094  126.786276

In [8]:
african_recipe_mol_edge.head(1000)

     recipe_id  molecule_id      S_rm  cuisine
0           98          247  0.004588  African
1           98          261  0.003000  African
2           98          402  0.003692  African
3           98          527  0.004588  African
4           98          650  0.004459  African
..         ...          ...       ...      ...
995        670        73750  0.000473  African
996        670        75552  0.000521  African
997        670        79828  0.000521  African
998        670        80046  0.000473  African
999        670        98280  0.000521  African

[1000 rows x 4 columns]